name: build
on:
  push:
    branches: master

jobs:
  # ベースライン
  # build_no_cache:
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - uses: actions/checkout@master
  #     - name: Build
  #       run: docker build .

  # BuildKitのみ
  # build_no_cache_buildkit:
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - uses: actions/checkout@master
  #     - name: Build
  #       env:
  #         DOCKER_BUILDKIT: 1
  #       run: docker build .

  # build_with_docker_save_load:
  #   runs-on: ubuntu-18.04
  #   steps:
  #   - uses: actions/checkout@master
  #   - id: cache-docker
  #     uses: actions/cache@v1
  #     with:
  #       path: /tmp/docker-save
  #       key: docker-save-${{ hashFiles('Dockerfile') }}
  #   - run: docker load -i /tmp/docker-save/snapshot.tar || true
  #     if: steps.cache-docker.outputs.cache-hit == 'true'
  #   - run: docker build . -t thing --cache-from=thing-cache
  #   - run: docker tag thing thing-cache && mkdir -p /tmp/docker-save && docker save thing-cache -o /tmp/docker-save/snapshot.tar && ls -lh /tmp/docker-save || true
  #     if: always() && steps.cache-docker.outputs.cache-hit != 'true'

  # cache-from -build-arg
  # cache-from-with-build-arg:
  #   runs-on: ubuntu-18.04
  #   steps:
  #   - uses: actions/checkout@master
  #   - name: Build
  #     env:
  #       DOCKER_BUILDKIT: 1
  #     run: |
  #       echo $SHA
  #       docker build --tag adachikun/githubactionsbuild:latest --cache-from=adachikun/githubactionsbuild:latest --build-arg BUILDKIT_INLINE_CACHE=1 .

  #   - name: docker login
  #     env:
  #       DOCKERHUB_USER: ${{ secrets.DOCKER_USERNAME }}
  #       DOCKERHUB_PASS: ${{ secrets.DOCKER_PASSWORD }}
  #     run: docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
  #   - name: push image
  #     run: docker push adachikun/githubactionsbuild:latest

      # build-push-action
      # https://github.com/marketplace/actions/build-and-push-docker-images
      # - name: Build
      #   uses: docker/build-push-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #     repository: adachikun/githubactionsbuild
      #     tags: latest
      #     push: false


      # build-push-action + Buildkit
      # https://github.com/marketplace/actions/build-and-push-docker-images
      # - name: Build
      #   uses: docker/build-push-action@v1
      #   env:
      #     DOCKER_BUILDKIT: 1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #     repository: adachikun/githubactionsbuild
      #     tags: latest
      #     push: false


  build-push-action-cache:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
      # build-push-action + Buildkit + cache + 2
      # https://github.com/marketplace/actions/build-and-push-docker-images
    - name: Build
      uses: docker/build-push-action@v1
      env:
        DOCKER_BUILDKIT: 1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: adachikun/githubactionsbuild
        tags: latest
        cache_froms: adachikun/githubactionsbuild:latest
        build_args: BUILDKIT_INLINE_CACHE=1
