name: build
on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      # ベースライン
      # - name: Build
      #   run: docker build .

      # BuildKitのみ
      # - name: Build
      #   env:
      #     DOCKER_BUILDKIT: 1
      #   run: docker build .

      # build-push-action
      # https://github.com/marketplace/actions/build-and-push-docker-images
      - name: build-push-action
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: adachikun/githubactionsbuild
          tags: latest
          push: false
