name: deploy
on:
  push:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Build
        env:
        run: |
          docker build .
